config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destory]
  resources :products, only: [:show]
  resources :cart_details
  resources :commonly_used_destinations

  resources :orders do
    member do
      get :confirm
      get :address
    end
  end

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  root 'static_pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  has_many :order_details, foreign_key: "order_id", dependent: :destroy
  has_many :products, through: :order_details, source: :product
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_stock_before_step_to_create_address, only: [:address, :confirm]

  def address
    @address = current_user.commonly_used_destinations.build
    @address_list = CommonlyUsedDestination.where("user_id = ?", current_user.id)
  end

  def confirm
    @address = CommonlyUsedDestination.find_by("id = ?", params[:id])
    @products_in_cart = CartDetail.where("user_id = ?", current_user.id)
    if @address.nil? || @address.user_id != current_user.id
      redirect_to address_order_path(current_user)
    end
  end

  private

  def check_stock_before_step_to_create_address
    cart_details = current_user.cart_details
    cart_details.each do |cart_detail|
      if cart_detail.quantity > cart_detail.product.stock
        flash[:error] = "在庫不足"
        redirect_to cart_details_path
      end
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_address_confirm.html.erb
<%= link_to "この住所使う", confirm_order_path(address_list) %>

app/views/orders/_address_delete.html.erb
<%= link_to "削除", commonly_used_destination_path(address_list), 
                    data: {confirm: "本当ですか?"}, method: :delete %>

app/views/orders/_address_edit.html.erb
<%= link_to "修正", edit_commonly_used_destination_path(address_list) %>

app/views/orders/_address_form.html.erb
<font size="1">配送情報登録しますか？</font>

<%= form_for(@address) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.hidden_field :user_id %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.submit "ok", class: "btn btn-small" %>
<% end %>

app/views/orders/_address_list.html.erb
<% @address_list.each do |address_list| %>
<p>
<li>
  <span class="content">名前 : <%= address_list.name %></span>
  <span><%= address_list.address %></span>
  <span>(<%= address_list.phone %>)</span>
  <span></span>
  <br><%= render partial: 'address_confirm', locals: { address_list: address_list } %> | 
      <%= render partial: 'address_delete' , locals: { address_list: address_list } %> | 
      <%= render partial: 'address_edit'   , locals: { address_list: address_list } %>
  </br>
</li>
</p>
<% end %>

app/views/orders/_confirm_order.html.erb
ここに確定ボタン追加予定

app/views/orders/address.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <%= render "address_form" %>
    </div>
    <div class="span10">
      <div class="column-row">
        <div class="span2"></div>
        <div class="span10"><%= render "address_list" %></div>
      </div>
    </div>
  </div>
</div>

app/views/orders/confirm.html.erb
<br>
<li>注文者 : <%= @address.name %></li>
<li>配送値 : <%= @address.address %></li>
<li>電話番語 : <%= @address.phone %></li>
</br>
<div class="row">
  <div class="span5">
    <%  @products_in_cart.each do |product_in_cart| %>
      <%= image_tag(product_in_cart.product.picture, size: "100x100") %>
      <%= product_in_cart.product.name %>
      <%= product_in_cart.price %>円
      | 数量 : <%= product_in_cart.quantity %>
    <% end %>
  </div>
  <div class="span3 offset2"><%= render "confirm_order" %></div>
</div>