config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destory]
  resources :products, only: [:show]
  resources :cart_details
  resources :commonly_used_destinations

  resources :orders do
    member do
      get :confirm
      get :address
    end
  end

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  root 'static_pages#home'

end

app/models/cart_detail.rb
class CartDetail < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  default_scope -> { order('created_at DESC') }
  VALID_QUANTITY_REGEX = /\A[1-9]\z/
  validates :price, presence: true
  validates :quantity, presence: true, format: { with: VALID_QUANTITY_REGEX }
end

app/controllers/cart_details_controller.rb
class CartDetailsController < ApplicationController
  before_action :signed_in_user, only: [:index, :create, :destroy, :update]
  before_action :check_stock_create, only: [:create]
  before_action :check_stock_update, only: [:update]
  before_action :check_price, only: [:index]

  def index
    @cart_details = get_current_cart_by_current_user
  end

  def create
    selected_product = Product.find_by("id = ?", params[:cart_detail][:product_id])
    selected_quantity = selected_quantity_params
    if current_user.add_product_to_cart(selected_product, selected_quantity)
      redirect_to cart_details_path
    else
      flash[:error] = "カートには一つの商品にあたり最大9個入れることができます"
      redirect_to cart_details_path
    end
  end

  def destroy
    product_in_the_cart = CartDetail.find_by("id = ?", params[:id])
    if product_in_the_cart.nil?
      flash[:error] = "すでに商品は削除されました"
      redirect_to cart_details_path
    else
      product_in_the_cart.destroy
      flash[:success] = "正常に削除されました"
      redirect_to cart_details_path
    end
  end

  def update
    product_in_the_cart = CartDetail.find_by("id = ?", params[:id])
    if !product_in_the_cart.nil? 
      product_in_the_cart.update_attributes(quantity_params)
      selected_quantity = selected_quantity_params
      current_user.update_product_in_cart(product_in_the_cart, selected_quantity)
      flash[:success] = "正常に変更されました"
      redirect_to cart_details_path
    else
      flash[:error] = "すでに商品は削除されました"
      redirect_to cart_details_path
    end
  end

  private

  def check_price
    cart_details = get_current_cart_by_current_user
    cart_details.each do |cart_detail|
      price_per_one = (cart_detail.price / cart_detail.quantity)
      if price_per_one != cart_detail.product.price
        price_per_quantity = cart_detail.product.price * cart_detail.quantity
        context = "#{cart_detail.product.name}の値段が変更されました.
                   #{price_per_one}円 -> #{cart_detail.product.price}円"
        flash.now[:notice] = "#{context}"
        cart_detail.update_attribute(:price, price_per_quantity)
      end
    end
  end
    
  def check_stock_create
    product = Product.find_by("id = ?", params[:cart_detail][:product_id])
    cart_detail = CartDetail.find_by(user_id: current_user.id, product_id: product.id)
    if cart_detail.nil?
      if selected_quantity_params.to_i > product.stock
        flash[:error] = "在庫不足"
        redirect_to product_path(product)
      end
    else
      if(cart_detail.quantity.to_i + selected_quantity_params.to_i) > product.stock 
        flash[:error] = "在庫不足"
        redirect_to product_path(product)
      end
    end
  end

  def check_stock_update
    product = Product.find_by("id = ?", params[:cart_detail][:product_id])
    if selected_quantity_params.to_i > product.stock
      flash[:error] = "在庫不足"
      redirect_to product_path(product)
    end
  end

  def quantity_params
    params.require(:cart_detail).permit(:quantity)
  end

  def selected_quantity_params
    params[:cart_detail][:quantity]
  end
end

app/helpers/cart_details_helper.rb
module CartDetailsHelper
  
  def get_current_cart_by_current_user
    CartDetail.where("user_id = ?", current_user.id)
  end 
end

app/views/cart_details/_order_form.html.erb
<% unless get_current_cart_by_current_user.empty? %>
  <%= link_to "レジに進む", address_order_path(current_user), class: "btn btn-small" %>
<% else %>
  <% flash.now[:notice] = "カートに商品を入れてください" %>
<% end %>

app/views/cart_details/index.html.erb
<% @cart_details.each do |cart_detail| %>
  <%= link_to image_tag(cart_detail.product.picture, :size => "100x100"), 
                      controller: "products", action: "show" ,id: cart_detail.product.id %>
  <%= cart_detail.price %>円  
  <%= cart_detail.quantity %>個 | 
  在庫 : <%= cart_detail.product.stock %>
  <%= form_for(cart_detail) do |f| %>
    <div>
    <% cart_detail.product.stock < 9 ? max = cart_detail.product.stock : max = 9 %>
    <%= f.number_field :quantity, min: 1, max: "#{max}" %>
    <%= f.hidden_field :product_id, value: cart_detail.product.id %>
    <%= f.submit "変更", class: "btn btn-small", data: { disable_with: "送信中"} %>
    <%= link_to "商品削除", cart_detail, method: :delete, data: { confirm: "本当ですか?" } %>
    </div>
  <% end %>    
<% end %>
<%= render "order_form" %>

app/views/cart_details/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <% @cart_details.each do |cart_detail| %>
        <% display_price = synchronization_product_price(cart_detail) %>
          <%= link_to image_tag(cart_detail.product.picture, :size => "100x100"), 
                          controller: "products", action: "show" ,id: cart_detail.product.id %>
          <%= display_price %>円
          <%= link_to "商品削除", cart_detail, method: :delete, data: { confirm: "本当ですか?" } %> 
          <%= form_for(cart_detail) do |f| %>
          在庫 : <%= cart_detail.product.stock %>
            <% if cart_detail.product.stock < 9 %>
              <% max = cart_detail.product.stock %>
              <%= f.number_field :quantity, min: 1, max: "#{max}" %>
              <%= f.submit "変更", class: "btn btn-small", data: { disable_with: "送信中"} %>
            <% else %>
              <%= f.number_field :quantity, min: 1, max: 9 %>
              <%= f.submit "変更", class: "btn btn-small", data: { disable_with: "送信中"} %>
            <% end %>
          <% end %>
      <% end %>
    </div>
    <div class="span10">
      <%= render "order_form" %>
    </div>
  </div>
</div>